# Generated by Django 3.0.4 on 2020-07-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200729_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
